[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "f37575bd1ab07b0983d8d10fdc0f630c866c43ba"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "e93ed6e0b072e44442671dfcc50e6b3bbfd2091910adfe4a724aefa7a19c0e09"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.aarch64-apple-darwin.tar.gz"
[[OpenFHE]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20e629f05ea9c4fac1d7e8ed015898b45fef31c9"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "873cb19e21e76b0866f17ebb21038a3f67333c8ca785507bb1d079fd4686f301"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "aarch64"
git-tree-sha1 = "e969047dfdaf77b6a0e2046f8f7f66887c1a4c1d"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "dd3a69c0abfcb8afaa90854bde0f1f98505ebd3c9acf85ee80344652fb1c9fbc"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.aarch64-unknown-freebsd.tar.gz"
[[OpenFHE]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0caf2bc58ff5a39bf900b9c8cba05bfbbeb1149"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "ffcfc63eed0908bc5c9f9004204692657287c5331898330d4ea87ae2fa3c708b"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[OpenFHE]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fc8a738114092168882b2bf6ee4f75e7d4bdbd0"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "ad9e3141929e8c86a5ba91731eaeaf614c7494da1a22d27d06a8e7a80d3f7861"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OpenFHE]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c502d2f8f0ae24302ebf5a5f51e7373f9907b9a4"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "2cb76e6d20353be038ff49660f76b447e8dadfb5640378e7ea3e88ab79800682"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "a8e4b3d40214a93f633e8b911f7b47adb897c06b"
os = "macos"

    [[OpenFHE.download]]
    sha256 = "83a9263f2cbf1f27297bb2cb7b7030fd8314bb976c476d9825a4b972ea90b72a"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.x86_64-apple-darwin.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6df11881958b1d46321d89541560a0fbf3ec26a0"
libc = "glibc"
os = "linux"

    [[OpenFHE.download]]
    sha256 = "3b3d67b570a05ccabad1974ba84825fbe15a26412185055d1c937d750834d4a4"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenFHE]]
arch = "x86_64"
git-tree-sha1 = "ee2a5a466963407d9fd6984cd0bf51db7a176cf2"
os = "freebsd"

    [[OpenFHE.download]]
    sha256 = "bbb27142cebb120fa535b99e868f18c73c46424d931d86260ae5de3429c654cf"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.x86_64-unknown-freebsd.tar.gz"
[[OpenFHE]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2541a4dbe958c931425079be0a45c8a60b8561c"
os = "windows"

    [[OpenFHE.download]]
    sha256 = "753bac513a34415d6b9c091dd7758754d87d83f502d21e6df3f2e23022cb21eb"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_jll.jl/releases/download/OpenFHE-v1.5.0+0/OpenFHE.v1.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
