# Autogenerated wrapper script for OpenFHE_jll for aarch64-apple-darwin-julia_version+1.10.0
export libOPENFHEbinfhe, libOPENFHEcore, libOPENFHEpke

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("OpenFHE")
JLLWrappers.@declare_library_product(libOPENFHEbinfhe, "@rpath/libOPENFHEbinfhe.1.dylib")
JLLWrappers.@declare_library_product(libOPENFHEcore, "@rpath/libOPENFHEcore.1.dylib")
JLLWrappers.@declare_library_product(libOPENFHEpke, "@rpath/libOPENFHEpke.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libOPENFHEbinfhe,
        "lib/libOPENFHEbinfhe.1.2.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOPENFHEcore,
        "lib/libOPENFHEcore.1.2.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOPENFHEpke,
        "lib/libOPENFHEpke.1.2.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
