# Autogenerated wrapper script for OpenFHE_jll for x86_64-w64-mingw32-cxx11
export libOPENFHEbinfhe, libOPENFHEcore, libOPENFHEpke

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("OpenFHE")
JLLWrappers.@declare_library_product(libOPENFHEbinfhe, "libOPENFHEbinfhe.dll")
JLLWrappers.@declare_library_product(libOPENFHEcore, "libOPENFHEcore.dll")
JLLWrappers.@declare_library_product(libOPENFHEpke, "libOPENFHEpke.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libOPENFHEbinfhe,
        "bin\\libOPENFHEbinfhe.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOPENFHEcore,
        "bin\\libOPENFHEcore.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libOPENFHEpke,
        "bin\\libOPENFHEpke.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
